# Generated by Django 5.0.3 on 2024-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blogtitle', models.CharField(max_length=200)),
                ('blogemail', models.EmailField(max_length=100)),
                ('blogdesc', models.TextField(max_length=500)),
                ('blogthumbnail', models.ImageField(upload_to='images')),
                ('blogdate', models.DateField()),
            ],
        ),
    ]
