# Generated by Django 5.0.3 on 2024-03-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blogemail',
            field=models.EmailField(max_length=150),
        ),
    ]
