# Generated by Django 5.0.3 on 2024-03-17 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_blogthumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blogthumbnail',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
